platform :ios, '9.0'

target 'WeatherApp' do
	pod 'AFNetworking'
    pod 'JSONModel'
    pod 'Realm'
    pod 'Reachability'
    pod 'SVProgressHUD'
    pod 'THProgressView'
    pod 'NoNetworkViewController'
end
